brownfield_django/urls.py
import os

from brownfield_django.main.views import (
    HomeView, CCNMTLHomeView, CCNMTLCourseDetail,
    TeamHomeView, EditTeamsView, ShowTeamsView,
    ActivateCourseView, BrownfieldDemoView,
    TeamHistoryView, TeamInfoView, TeamPerformTest,
    TeamCSV, ShowProfessorsView, ArchiveCourseView, TeamSignContract)
from brownfield_django.main.views import CourseViewSet, UserViewSet, \
    DocumentViewSet, StudentViewSet, TeamViewSet, InstructorViewSet, \
    RestrictedFlatPage, RestrictedFile
from django.conf import settings
from django.urls import include, path, re_path
from django.contrib import admin
from django.views.generic import TemplateView
import django.views.static
from django_cas_ng import views as cas_views
from rest_framework import routers


admin.autodiscover()

simulation_root = os.path.join(os.path.dirname(__file__),
                               '../media/', 'flash')


router = routers.DefaultRouter()
router.register(r'course', CourseViewSet)
router.register(r'user', UserViewSet)
router.register(r'document', DocumentViewSet)
router.register(r'student', StudentViewSet)
router.register(r'instructor', InstructorViewSet)
# flash uses team in url, this is router for team on dashboard
router.register(r'eteam', TeamViewSet)

try:
    static_flash_domain = settings.AWS_STORAGE_BUCKET_NAME + \
        '.s3.amazonaws.com'
except AttributeError:
    static_flash_domain = settings.STATIC_URL

urlpatterns = [
    re_path(r'^accounts/', include('registration.backends.default.urls')),
    path('cas/login', cas_views.LoginView.as_view(),
         name='cas_ng_login'),
    path('cas/logout', cas_views.LogoutView.as_view(),
         name='cas_ng_logout'),

    re_path(r'^api/', include(router.urls)),
    re_path(r'^api-auth/', include('rest_framework.urls',
                                   namespace='rest_framework')),
    re_path(r'^$', HomeView.as_view()),
    re_path(r'^ccnmtl/home/(?P<pk>\d+)/$', CCNMTLHomeView.as_view()),
    re_path(r'^course_details/(?P<pk>\d+)/$', CCNMTLCourseDetail.as_view()),
    re_path(r'^activate_course/(?P<pk>\d+)/$', ActivateCourseView.as_view()),
    re_path(r'^archive_course/(?P<pk>\d+)/$', ArchiveCourseView.as_view()),
    re_path(r'^edit_teams/(?P<pk>\d+)/$', EditTeamsView.as_view()),
    re_path(r'^show_teams/(?P<pk>\d+)/$', ShowTeamsView.as_view()),
    re_path(r'^show_instructors/$', ShowProfessorsView.as_view()),
    re_path(r'^demo/play$', TemplateView.as_view(
        template_name="main/flvplayer.html")),
    re_path(r'^demo/info/', BrownfieldDemoView.as_view()),
    re_path(r'^demo/history/', BrownfieldDemoView.as_view()),
    re_path(r'^demo/test/$', BrownfieldDemoView.as_view()),
    re_path(r'^team/home/(?P<pk>\d+)/$',
            TeamHomeView.as_view(), name="team-home"),
    re_path(r'^team/(?P<pk>\d+)/play$', TeamHistoryView.as_view(),
            name='team-history'),
    re_path(r'^team/(?P<pk>\d+)/history/', TeamHistoryView.as_view()),
    re_path(r'^team/(?P<pk>\d+)/info/$', TeamInfoView.as_view()),
    re_path(r'^team/(?P<pk>\d+)/test/$', TeamPerformTest.as_view()),
    re_path(r'^team/sign_contract/$',
            TeamSignContract.as_view(), name='sign-contract'),
    re_path(r'^site_history/$', TemplateView.as_view(
        template_name="interactive/site_history.html")),
    re_path(r'^team_csv/(?P<pk>\d+)/$', TeamCSV.as_view(), name='team-csv'),
    re_path('^contact/', include('contactus.urls')),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^_impersonate/', include('impersonate.urls')),
    re_path(r'^stats/$', TemplateView.as_view(template_name="stats.html")),
    re_path(r'smoketest/', include('smoketest.urls')),
    re_path(r'^instructors/files/(?P<path>.*)$', RestrictedFile.as_view()),
    re_path(r'^instructors/', RestrictedFlatPage.as_view()),

    re_path(r'^simulation/demo/$', TemplateView.as_view(
        template_name='simulation/demo.html')),

    re_path(r'^simulation/walkthrough/(?P<path>.*)$',
            django.views.static.serve,
            {'document_root': simulation_root}),

    re_path(r'^uploads/(?P<path>.*)$', django.views.static.serve,
            {'document_root': settings.MEDIA_ROOT})
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

brownfield_django/main/models.py
from django.contrib.auth.models import User
from django.db import models

from brownfield_django.main.document_links import all_documents


PROFILE_CHOICES = (
    ('AD', 'Administrator'),
    ('TE', 'Teacher'),
    ('ST', 'Student'),
)


class Course(models.Model):
    '''
    Course Model
    '''
    name = models.CharField(max_length=255)
    startingBudget = models.PositiveIntegerField(default=60000)
    enableNarrative = models.BooleanField(default=True)
    message = models.TextField(max_length=255, default='')
    active = models.BooleanField(default=False)
    archive = models.BooleanField(default=False)
    professor = models.ForeignKey(User, related_name="taught_by", null=True,
                                  default=None, blank=True,
                                  on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        super(Course, self).save(*args, **kwargs)
        if self.document_set.count() == 0:
            for doc in all_documents:
                d = Document.objects.create(
                    course=self, name=doc['name'], link=doc['link'])
                self.document_set.add(d)

    def get_students(self):
        return self.userprofile_set.filter(profile_type='ST')

    def get_student_users(self):
        profile_set = self.get_students()
        user_set = User.objects.filter(profile__in=profile_set)
        return user_set

    def get_teams(self):
        return self.team_set.filter(course=self)

    def get_documents(self):
        documents = Document.objects.filter(course=self)
        return documents


class Document(models.Model):
    course = models.ForeignKey(Course, null=True,
                               default=None, blank=True,
                               on_delete=models.CASCADE)
    name = models.CharField(max_length=255, default='')
    link = models.CharField(max_length=255, default='')
    visible = models.BooleanField(default=False)

    class Meta:
        ordering = ['name']


class Team(models.Model):
    '''
    Students log in as a team, teams hold progress.
    '''
    user = models.OneToOneField(User, null=True, default=None,
                                blank=True, related_name="team",
                                on_delete=models.CASCADE)
    course = models.ForeignKey(Course, null=True, default=None, blank=True,
                               on_delete=models.CASCADE)
    signed_contract = models.BooleanField(default=False)
    budget = models.PositiveIntegerField(default=65000)
    '''
    We need a plain text copy of the password to email the students
    '''
    team_passwd = models.CharField(max_length=255, default="", blank=True)

    def __str__(self):
        name = ""
        try:
            name = self.user.username
        except AttributeError:
            name = "TeamUser"
        return name

    class Meta:
        ordering = ["user"]

    def get_team_members(self):
        '''Should I explicitly set it to return
        only profiles of 'ST' type?'''
        return self.userprofile_set.all()

    def get_team_history(self):
        history = History.objects.filter(team=self)
        return history


class UserProfile(models.Model):
    '''UserProfile adds extra information to a user,
    and associates the user with a course.'''
    user = models.OneToOneField(User, related_name="profile",
                                on_delete=models.CASCADE)
    profile_type = models.CharField(max_length=2, choices=PROFILE_CHOICES)
    '''Leaving course null/blank because admins and
    teachers do not necessarily belong to a course.'''
    archive = models.BooleanField(default=False)
    course = models.ForeignKey(Course, null=True, default=None, blank=True,
                               on_delete=models.CASCADE)
    team = models.ForeignKey(Team, null=True, default=None, blank=True,
                             on_delete=models.CASCADE)
    tmp_passwd = models.CharField(max_length=255, default="", blank=True)

    def __str__(self):
        return self.user.username

    class Meta:
        ordering = ["user"]

    def display_name(self):
        return '%s - %s' % (self.user.first_name, self.user.last_name)

    def is_student(self):
        return self.profile_type == 'ST'

    def is_teacher(self):
        return self.profile_type == 'TE'

    def is_admin(self):
        return self.profile_type == 'AD'

    def role(self):
        if self.is_admin():
            return "administrator"
        elif self.is_teacher():
            return "faculty"
        else:
            return "student"

    def get_absolute_url(self):
        # Note that a url of '/' can trigger a redirect loop in HomeView.
        url = '/'

        if self.is_teacher():
            url = '/ccnmtl/home/%s/' % (self.id)
        elif self.is_admin():
            url = '/ccnmtl/home/%s/' % (self.id)
        else:
            try:
                team = Team.objects.get(user=self.user.pk)
                url = '/team/home/%s/' % (team.pk)
            except Team.DoesNotExist:
                pass

        return url


class History(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    date = models.CharField(max_length=16)
    description = models.TextField()
    cost = models.IntegerField(default=0)

    def __str__(self):
        return '%s - %s' % (self.description, self.team)

    def get_tests_performed(self):
        performed_tests = PerformedTest.objects.filter(history=self)
        return performed_tests

    def get_information(self):
        information = Information.objects.filter(history=self)
        return information


class PerformedTest(models.Model):
    history = models.ForeignKey(History, null=True, default=None, blank=True,
                                on_delete=models.CASCADE)
    x = models.IntegerField(default=0)
    y = models.IntegerField(default=0)
    z = models.IntegerField(default=0)
    testDetails = models.CharField(default="", max_length=255)
    testNumber = models.IntegerField(default=0)
    paramString = models.CharField(default="", max_length=255)

    def __str__(self):
        return '%s - %s' % (self.testDetails, self.paramString)


class Information(models.Model):
    """
    Comment from Old Code:
        Documents and News Items made available to or found by the Team
    """
    history = models.ForeignKey(History, null=True, default=None, blank=True,
                                on_delete=models.CASCADE)
    infoType = models.CharField(default="", max_length=255, blank=True)
    internalName = models.CharField(default="", max_length=255, blank=True)

    def __str__(self):
        return '%s - %s' % (self.infoType, self.internalName)

brownfield_django/templates/main/ccnmtl/home_dash/ccnmtl_home.html
{% extends 'base.html' %}
{% load static %}

{% block bbjs %}
    <script type="text/javascript" src="{% static 'js/ccnmtljs/bb_models.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/ccnmtljs/bb_collections.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/ccnmtljs/bb_views.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/ccnmtljs/bb_control_views.js' %}"></script>
{% endblock %}

{% block js %}
    <script type="text/template" id="course-list-template">
        <div class="course-name-inside">
        <button class="btn btn-default course_name"><span class="glyphicon glyphicon-th-list"></span> <strong><%= name %></strong> Details</button>
        </div>
        <button class='btn btn-xs btn-default edit-crs pull-right'><span class="glyphicon glyphicon-pencil"></span> Edit Course </button>
    </script>

    <script type="text/template" id="course-edit-template">
        <form id="create-edit-form" method="" action="">
            <span class="course-name-block">
                <label for="edit_course_name">Name:</label>
                <input id="edit_course_name" maxlength="255" name="name" type="text" value="<%= name %>"/><br />
            </span>
            <span class="course-budget-block">
		        <label for="edit_course_startingBudget">StartingBudget:</label> 
			    <input id="edit_course_startingBudget" min="0" name="startingBudget" type="number" value=<%= startingBudget %> /><br />
            </span>
            <span class="course-message-block">
			    <label for="edit_course_message">Message:</label> 
			    <textarea form="create-edit-form" cols="80" id="edit_course_message" name="edit_message" rows="10"><%= message %></textarea><br />
			</span>
            {% comment %}
            <span class="course-professor-block">
			{% if request.user.profile.is_admin %}
				<label for="edit_professor">Professor:</label>
				<select id="edit_professor" name="professor">
               	</select><br />
            {% endif %}
            </span>
            {% endcomment %}
            <span class="conf-del" style="display:none;">
                <b class="pull-left" style='color:red'>
                    Are you sure you want to archive this course?
                </b>
                <button class='btn btn-xs btn-danger pull-right conf-arch' type="button">
                    Yes Archive
                </button>
                <button class='btn btn-xs btn-success pull-right cancel-arch' type="button">
                    Cancel
                </button>
            </span>
            <span class="reg-btn">
                <button class='btn btn-default btn-xs conf-archive-course' type="button">
                    Archive Course
                </button>
                <button class='btn btn-default btn-xs save-edit-course' type="button">
                    Save
                </button>
                <button class='btn btn-default btn-xs cncl-edit-crs' type="button">
                    Cancel
                </button>
            </span>
        </form>
        <br />
    </script>
    
    
    {% if request.user.profile.is_admin %}
    <script type="text/template" id="instructor-list-template">
        <div class="instructor-list-inside">
            <span class="instructor"><label for="instructor">Instructor:</label>&nbsp;<%= first_name %> <%= last_name %></span>
            <span class="email"><label for="email">Email:</label>&nbsp;<%= email %></span>
        </div>
        <div class="instructor-button-inside">
            <span class="conf-del"  style="display:none;">
                <b>Are you sure you want to remove this instructor?</b>
                <button class='btn btn-default btn-xs pull-right cancel-arch-inst'> Cancel </button>
                <button class='btn btn-default btn-xs pull-right conf-arch'> Yes Remove </button>
            </span>
            <span class="reg-btn">
                <button class='btn btn-default btn-xs pull-right conf-archive-inst'> Remove Instructor </button>
                <button class='btn btn-default btn-xs pull-right ed-inst'> Edit Instructor </button>
            </span>
        </div>

    </script>


    <script type="text/template" id="instructor-edit-template">
    <form class="edit-instructor-frm" method="" action="" style="display: inline;">
        {% csrf_token %}
        <span class="inst-edt-first-name">
            <label>First Name: </label>
            <input type="text" placeholder="First Name: " class="edt-frst-name" value="<%= first_name %>" />     
        </span>
        <span class="inst-edt-last-name">
            <label>Last Name: </label>
            <input type="text" placeholder="Last Name: " class="edt-last-name" value="<%= last_name %>" /> 
        </span>
        <span class="inst-edt-email">
            <label>Email: </label>
            <input type="text" placeholder="Email: " class="edt-email" value="<%= email %>" />
        </span>
        <button class='btn btn-xs btn-default pull-right cncl-edit-inst'> Cancel </button>
        <button class='btn btn-default btn-xs pull-right save-edit-instructor'> Save Changes </button>
    </form>
    </script>
    {% endif %}


    <script type="text/javascript">
        jQuery(document).ready(function () {
            var control_view = new ManageCoursesView({
                el: jQuery('.course-creation-area'),
                listEl: jQuery('.course-list'),
                user_id: "{{request.user.id}}"
            });

           {% if request.user.profile.is_admin %}
               var instructor_controls = new ManageInstructorsView({
        	       el: jQuery('.instructor_controls')
               });
           {% endif %}
        });
    </script>
{% endblock %}

{% block content %}

  <ul class="nav nav-tabs instructor-nav">
    <li class="active"><a href="#course-list" data-toggle="tab">Courses</a></li>
    <li><a href="/simulation/demo/">Simulation</a></li>
    <li><a href="/instructors/resources/">Resources</a></li>
  </ul>
 
  <div class="instructor tab-content">{% csrf_token %}
    {% include "main/ccnmtl/home_dash/course_list_tab.html" %}
    {% include "main/ccnmtl/home_dash/demo_tab.html" %}
  </div>
{% endblock %}

brownfield_django/templates/main/ccnmtl/home_dash/course_list_tab.html
<div class="tab-pane active" id="course-list">
    <div class="course-creation-area">
      <div class='course-header'>
        <h3>
          Courses
        </h3>
        <button class="btn btn-default add-crs pull-right">
            <span class="glyphicon glyphicon-plus"></span>
          Add New Course
        </button>
      </div><!-- End div course-header -->
      <div class='course-form-area'>  
        <div class='accoridion'>
          <form id="create-course-form" method="" action="" style="display: none;">
                {% csrf_token %}
                <h4 id="frm-title">Add New Course:</h4>
                <span class="course-name-block">
                    <label for="id_course_name">Name:</label>
                    <input id="id_course_name" maxlength="255" name="name" type="text" placeholder="Course Name" />
                    <br />
                </span>
                <span class="course-budget-block">
		            <label for="id_course_startingBudget">Starting Budget:</label> 
			        <input id="id_course_startingBudget" min="0" name="startingBudget" type="number" placeholder="60000" />
			        <br />
			    </span>
			    <span class="course-message-block">
			        <label for="id_course_message">Message:</label> 
			        <textarea cols="80" id="id_course_message" name="message" rows="10" placeholder="Course Message Here" ></textarea><br />
			    </span>
			    <span class="course-professor-block">
			        {% if request.user.profile.is_admin %}
				        <label for="id_professor">Professor:</label>
				        <select id="id_professor" name="professor">

               	        </select><br />
                    {% endif %}
                </span>
                <input type="submit" value="Save Course" class="submit btn btn-default"/>
                <button class='btn btn-default cncl-add-crs' type="button">
                    Cancel
                </button>
              </form> 
            </div> <!-- End .accordion -->
        </div> <!-- End course from area -->

        <div class="course-list"></div>
    </div> <!-- End .course-creation-area -->


    <br /><br />
    {% if request.user.profile.is_admin %}
    <div class='instructor_controls'>
        <div class='instructor-header'>
            <h3>
                Instructors
            </h3>
            <button class="btn btn-default add-instructor-btn pull-right"><span class="glyphicon glyphicon-plus"></span> Add New Instructor</button>
        </div>
        <div class='instructor-form-area'>
            <form class="add-instructor-frm form-inline" method="post" action="" style="display: none;">
                {% csrf_token %}
                <h4>Add New Instructor</h4>
                <div class="form-group inst-first-name">
                    <label>First Name: </label>
                    <input type="text" class="instructor-frst-name" /> 
                </div>
                <div class="form-group inst-last-name">
                    <label>Last Name: </label>
                    <input type="text" class="instructor-last-name" /> 
                </div>
                <div class="form-group inst-email">
                    <label>Email: </label>
                    <input type="text" class="instructor-email" />
                </div>
                <button class='btn btn-default btn-xs cncl-add-inst' type="button">
                    Cancel
                </button>
                <button class='btn btn-primary btn-xs save-instructor' type="button">
                    Save
                </button>
            </form>
        </div> <!-- End Instructor Form Area -->
        <div class="instructor-list" >
            <!-- All instructors of courses will be inserted here -->
        </div>
    </div><!-- End instructor area -->
    {% endif %}
    <br /><br /><br /><br />
</div>

brownfield_django/templates/main/ccnmtl/home_dash/demo_tab.html
{% load static %}
<div class="tab-pane" id="demo">
    <div class='course-header'>
        <h3>PLAY BROWNFIELD ACTION</h3>
        <a class="btn btn-info btn-sm pull-right" role="button" data-toggle="collapse" href="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
            <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span> Help
        </a>
        <div class="clearfix"></div>
        <div class="collapse" id="collapseExample">
            <div class="well">
                The Adobe® Flash® Player is required to run the Brownfield Action
                interactive experience. For more information on installing
                and enabling Flash in your browser, please
                refer to the Adobe <a href="https://helpx.adobe.com/flash-player.html" target="_blank">Flash Player Help</a> page.
            </div>
        </div>
    </div>

    <br />
    <div id="main_content">
        <object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000"
                codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,0,0"
                width="761" height="521" id="bfa" align="middle">
            <param name="allowScriptAccess" value="sameDomain" />
            <!-- Static -->
            <param name="movie"
                   value="{% static 'flash/bfa.swf' %}" />

            <param name="quality" value="high" />
            <param name="bgcolor" value="#4d3e1b" />

            <!-- Domain & Static Do I need site.domain in front of static url?-->
            <param name="flashVars"
                   value="serverURL={{site.domain}}../../../demo/&amp;resourceRootURL={% static 'flash/' %}" />

            <!-- Static & Plugins & Domain & Static -->
            <embed src="{% static 'flash/bfa.swf' %}" quality="high" bgcolor="#4d3e1b" width="761"
                   height="521" name="bfa" align="middle" allowScriptAccess="sameDomain" type="application/x-shockwave-flash"
                   pluginspage="http://www.macromedia.com/go/getflashplayer"
                   flashVars="serverURL={{site.domain}}../../../demo/&amp;resourceRootURL={% static 'flash/' %}" />
        </object>

    </div>
    <div>
        <h3>Document Downloads</h3>
        <ul>
            <li><a href="{% static 'flash/documents/slCatalog.pdf' %}" target="_blank">Self-Lume catalog</a></li>
            <li><a href="{% static 'flash/documents/slBrochure.pdf' %}" target="_blank">Self-Lume brochure</a></li>
            <li><a href="{% static 'flash/documents/slMap.pdf' %}" target="_blank">Self-Lume property map</a></li>
            <li><a href="{% static 'flash/documents/contract.pdf' %}" target="_blank">Copy of contract text</a></li>
        </ul>
    </div>
</div> <!-- tab-pane -->

brownfield_django/templates/main/ccnmtl/home_dash/instructor_list.html
{% for professor in professors %}
<option value="{{professor.pk}}">{{professor.first_name}} {{professor.last_name}}</option>
{% empty %}
<option>add some instructors</option>
{% endfor %}